### ISSUE TITLE
Sovrapposizione date asse x - facets

### ISSUE THREAD

**Issue by moccelli** [CoMoS-SA/Covid-sssup#3]
Grafico 2&3: facets progressivi totale positivi per data e decessi complessivi
Da fare: la data sull'asse delle x si sovrascrive (specialmente tra il 01 mar e il 15 mar) - è possibile migliorare la lettura oppure sostituire la forma della data con 03-01 (mm-dd)?

**Comment by m-sostero** [comment]
Risolto, credo
